# Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[build-system]
requires = ["setuptools>=42", "wheel", "cython>=3.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = { attr = "_version.__version__" }

[project]
name = "NeMo-FW"
dynamic = ["version"]
description = "NeMo FW container"
requires-python = ">=3.10,<3.13"
license = { text = "Apache 2.0" }

# Define the core libraries
dependencies = [
    "nemo-export-deploy",
    "nemo-evaluator",
    "nemo-toolkit[audio]",
    "nemo-toolkit[tts]",
    "nemo-run",
    "nvidia-lm-eval",
]

[dependency-groups]
test = ["coverage>=7.8.1"]

[tool.uv.sources]
"nemo-export-deploy" = { path = "/opt/Export-Deploy", editable = true }
"nemo-evaluator" = { path = "/opt/Evaluator/packages/nemo-evaluator", editable = true }
"nemo-toolkit" = { path = "/opt/NeMo", editable = true }
"nemo-run" = { path = "/opt/Run", editable = true }

[tool.uv]
prerelease = "allow"
override-dependencies = [
    # Force core libraries to be installed from the local paths
    "megatron-core[dev,mlm]; sys_platform == 'never'", # Installed by MBridge
    "nemo-export-deploy @ /opt/Export-Deploy",
    "megatron-bridge; sys_platform == 'never'",        # Installed by MBridge
    "nemo-toolkit[audio] @ /opt/NeMo[audio]",
    "nemo-toolkit[tts] @ /opt/NeMo[tts]",
    "nemo-run @ /opt/Run",
    "transformer-engine; sys_platform == 'never'",     # Installed by MBridge
    # Pinning versions to solve conflicts
    "av==15.1.0",                               # Version 16.0.0 released recently and fails to install
    "webdataset==0.2.86",                       # fix for SB multimodal
    "pandas==2.2.3",
    "ctc_segmentation==1.7.4",
    "pyzmq==25.1.2",                            # @URL: https://github.com/NVIDIA/NeMo/issues/13625
    "tiktoken>=0.9.0",                          # let megatron-hub win over nemo-toolkit
    "datasets==3.1.0",
    "fsspec[http]>=2023.1.0,<=2024.9.0",
    "transformers; sys_platform == 'never'",    # Defer to transformers in MBridge install
    "packaging>=25.0",
    "nvidia-pytriton>=0.7.0",
    "urllib3>=2.0.7",
    "sh==2.2.2",
    "jupyter-core==5.8.1",
    "pillow==12.1.1",
    "protobuf==6.33.5",
    "cuda-python>=13.0.0",
    "multi-storage-client!=0.36.0",
    "levenshtein; sys_platform == 'never'",
    "pytest==8.4.2",
    "wandb>=0.25.0",
    "nvidia-lm-eval==25.11.1",
    "lilcom==1.8.1",
    "onnx==1.18.0",                             # TRT-LLM hard dependency
    "pytest-coverage; sys_platform == 'never'",
    "future; sys_platform == 'never'",
    # Never install the following dependencies
    "torch; sys_platform == 'never'",
    "torchvision; sys_platform == 'never'",
    "triton; sys_platform == 'never'",
    "nvidia-cublas-cu12; sys_platform == 'never'",
    "nvidia-cuda-cupti-cu12; sys_platform == 'never'",
    "nvidia-cuda-nvrtc-cu12; sys_platform == 'never'",
    "nvidia-cuda-runtime-cu12; sys_platform == 'never'",
    "nvidia-cudnn-cu12; sys_platform == 'never'",
    "nvidia-cufft-cu12; sys_platform == 'never'",
    "nvidia-cufile-cu12; sys_platform == 'never'",
    "nvidia-curand-cu12; sys_platform == 'never'",
    "nvidia-cusolver-cu12; sys_platform == 'never'",
    "nvidia-cusparse-cu12; sys_platform == 'never'",
    "nvidia-cusparselt-cu12; sys_platform == 'never'",
    "nvidia-nccl-cu12; sys_platform == 'never'",
    "tensorrt-llm; sys_platform == 'never'",
    "tensorrt; sys_platform == 'never'",
    "tensorrt-cu12-libs; sys_platform == 'never'",
    "vllm; sys_platform == 'never'",
    "bitsandbytes; sys_platform == 'never'",             # We prefer a source install
    "nvidia-resiliency-ext; sys_platform == 'never'",    # Installed by MBridge
    "nvidia-modelopt; sys_platform == 'never'",          # Installed by MBridge
    "setuptools>=82.0.0",                                # Required by vllm
    "open-clip-torch>=3.2.0",                            # Required by megatron-bridge, override nemo-toolkit's 2.24.0 constraint
    "lilcom!=1.8.2",
    "cryptography>=43.0.0,<47",                          # Required by megatron-bridge, override nemo-run's constraint
    "opencv-python; sys_platform == 'never'",            # Use the dependency from the base pytorch container
]
